// Generated by scripts/gen-enums.mjs from docs/openapi.json. Do not edit.
import type { components } from './schema'

export const AuditActionValues: components['schemas']['AuditAction'][] = [
  "LOGIN_SUCCESS",
  "LOGIN_FAILED",
  "USER_CREATED",
  "USER_UPDATED",
  "USER_ROLE_CHANGED",
  "USER_DEACTIVATED",
  "USER_REACTIVATED",
  "MASTER_CREATED",
  "MASTER_UPDATED",
  "MASTER_DEACTIVATED",
  "BOM_CREATED",
  "BOM_ITEMS_REPLACED",
  "BOM_ACTIVATED",
  "ROUTING_CREATED",
  "ROUTING_STEPS_REPLACED",
  "ROUTING_ACTIVATED",
  "INVENTORY_RECEIVE",
  "INVENTORY_ADJUSTMENT",
  "INVENTORY_ISSUE",
  "INVENTORY_RETURN",
  "ORDER_CREATED",
  "ORDER_UPDATED",
  "ORDER_PLANNED",
  "ORDER_MATERIALS_CHECKED",
  "ORDER_STARTED",
  "ORDER_CANCELLED",
  "ORDER_COMPLETED",
  "OPERATION_PROGRESS_REPORTED",
  "OPERATION_PROGRESS_CORRECTED",
]

export const AuditEntityValues: components['schemas']['AuditEntity'][] = [
  "user",
  "product",
  "material",
  "work_center",
  "bom",
  "routing",
  "inventory_transaction",
  "production_order",
  "production_order_material",
  "production_operation",
]

export const MaterialUnitValues: components['schemas']['MaterialUnit'][] = [
  "kg",
  "pcs",
  "m",
  "l",
]

export const OperationTypeValues: components['schemas']['OperationType'][] = [
  "CUTTING",
  "CNC",
  "WELDING",
  "PAINTING",
  "ASSEMBLY",
  "QC",
]

export const OrderStatusValues: components['schemas']['OrderStatus'][] = [
  "DRAFT",
  "MATERIAL_SHORTAGE",
  "READY_TO_PRODUCE",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
]

export const RoleValues: components['schemas']['Role'][] = [
  "ADMIN",
  "PRODUCTION_MANAGER",
  "WAREHOUSE",
  "WORKER",
]

export const TransactionTypeValues: components['schemas']['TransactionType'][] = [
  "RECEIVE",
  "RESERVE",
  "RELEASE",
  "ISSUE",
  "RETURN",
  "ADJUSTMENT",
]

export const VersionStatusValues: components['schemas']['VersionStatus'][] = [
  "DRAFT",
  "ACTIVE",
  "RETIRED",
]
