// Writes src/api/enums.ts: every enum of docs/openapi.json as a runtime array, so select
// options come from the backend contract instead of hand-copied lists (B2).
import { readFileSync, writeFileSync } from 'node:fs'

const spec = JSON.parse(readFileSync(new URL('../../docs/openapi.json', import.meta.url), 'utf8'))
const lines = [
  '// Generated by scripts/gen-enums.mjs from docs/openapi.json. Do not edit.',
  "import type { components } from './schema'",
  '',
]
for (const [name, schema] of Object.entries(spec.components.schemas).sort(([a], [b]) => a.localeCompare(b))) {
  if (!Array.isArray(schema.enum)) continue
  const values = schema.enum.map((value) => `  ${JSON.stringify(value)},`).join('\n')
  lines.push(`export const ${name}Values: components['schemas']['${name}'][] = [\n${values}\n]`, '')
}
writeFileSync(new URL('../src/api/enums.ts', import.meta.url), lines.join('\n'))
